######################## SETUP application.properties ########################

## General setup
server.port = 8080
vaadin.launch-browser = true

## Terminal setup - text color, formating, disable logging... 
spring.output.ansi.enabled = always  
logging.pattern.console = %cyan(%d{HH:mm:ss}) [%green(%level)]  %cyan(%msg%n)
logging.level.root = ERROR

## Files Uploading setup
spring.servlet.multipart.enabled = true
spring.servlet.multipart.max-file-size = 16MB
spring.servlet.multipart.max-request-size = 16MB

spring.profiles.active=local

# MongoDB Configuration (place holder)
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/mydatabase}
# Google API Configuration
google.api.key=${GOOGLE_API_KEY:YOUR_API_KEY_HERE}
#############################################################################