@startuml
class SplashActivity {
    - apiClient : ServerEndpointsAPI
    # onCreate(savedInstanceState : Bundle) : void
    - verifyUserWithServer(email : String) : void
    - navigateToLogin() : void
}
@enduml